# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewLocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewLocation

end


target 'FGRoute' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourApp
  pod 'FGRoute', '~> 1.0.7'

end